// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeTypesDocumentDataSlicesSlice = CommentsZoneSlice | HighlightsSlice;

/**
 * Content for Home Types documents
 */
interface HomeTypesDocumentData {
  /**
   * Título do Banner Principal field in *Home Types*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o título do banner principal
   * - **API ID Path**: home_types.titulo_banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_banner: prismic.KeyTextField;

  /**
   * Descrição do Banner Principal field in *Home Types*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Digite a descrição que será exibida no banner principal
   * - **API ID Path**: home_types.descricao_principal
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao_principal: prismic.RichTextField;

  /**
   * Imagem do Banner Principal field in *Home Types*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_types.imagem_banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_banner: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Home Types*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_types.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeTypesDocumentDataSlicesSlice>;
}

/**
 * Home Types document from Prismic
 *
 * - **API ID**: `home_types`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeTypesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomeTypesDocumentData>,
    "home_types",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Título de guia da página field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o título de exibição da guia da página
   * - **API ID Path**: settings.titulo_pagina
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_pagina: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = HomeTypesDocument | SettingsDocument;

/**
 * Item in *CommentsZone → Comentário padrão → Primary → Comentários*
 */
export interface CommentsZoneSliceDefaultPrimaryCommentsGroupItem {
  /**
   * Imagem do Autor field in *CommentsZone → Comentário padrão → Primary → Comentários*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: comments_zone.default.primary.comments_group[].comment_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  comment_image: prismic.ImageField<never>;

  /**
   * Nome do Autor field in *CommentsZone → Comentário padrão → Primary → Comentários*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o nome do autor do comentário
   * - **API ID Path**: comments_zone.default.primary.comments_group[].comment_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  comment_name: prismic.KeyTextField;

  /**
   * Descrição do comentário field in *CommentsZone → Comentário padrão → Primary → Comentários*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Digite o texto do comentário
   * - **API ID Path**: comments_zone.default.primary.comments_group[].comment_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  comment_description: prismic.RichTextField;
}

/**
 * Primary content in *CommentsZone → Comentário padrão → Primary*
 */
export interface CommentsZoneSliceDefaultPrimary {
  /**
   * Comentários field in *CommentsZone → Comentário padrão → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: comments_zone.default.primary.comments_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  comments_group: prismic.GroupField<
    Simplify<CommentsZoneSliceDefaultPrimaryCommentsGroupItem>
  >;
}

/**
 * Comentário padrão variation for CommentsZone Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CommentsZoneSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CommentsZoneSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CommentsZone*
 */
type CommentsZoneSliceVariation = CommentsZoneSliceDefault;

/**
 * CommentsZone Shared Slice
 *
 * - **API ID**: `comments_zone`
 * - **Description**: CommentsZone
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CommentsZoneSlice = prismic.SharedSlice<
  "comments_zone",
  CommentsZoneSliceVariation
>;

/**
 * Item in *SectionSliceZone → Highlights_image → Primary → Destaque com imagem*
 */
export interface HighlightsSliceHighlightsPrimaryHighlightImageItem {
  /**
   * Imagem de ícone do Destaque field in *SectionSliceZone → Highlights_image → Primary → Destaque com imagem*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: highlights.highlights.primary.highlight_image[].image_highlight
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_highlight: prismic.ImageField<never>;

  /**
   * Título do Destaque field in *SectionSliceZone → Highlights_image → Primary → Destaque com imagem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o título do destaque
   * - **API ID Path**: highlights.highlights.primary.highlight_image[].title_highlight
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_highlight: prismic.KeyTextField;

  /**
   * Descrição do Destaque field in *SectionSliceZone → Highlights_image → Primary → Destaque com imagem*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Digite a descrição do destaque
   * - **API ID Path**: highlights.highlights.primary.highlight_image[].description_highlight
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_highlight: prismic.RichTextField;
}

/**
 * Item in *SectionSliceZone → Highlights_text → Primary → Destaque de texto (sem imagem)*
 */
export interface HighlightsSliceHighlightsTextPrimaryHighlightTextItem {
  /**
   * Descrição do Destaque field in *SectionSliceZone → Highlights_text → Primary → Destaque de texto (sem imagem)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o texto de destaque
   * - **API ID Path**: highlights.highlightsText.primary.highlight_text[].highlight_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  highlight_description: prismic.KeyTextField;
}

/**
 * Primary content in *SectionSliceZone → Highlights_image → Primary*
 */
export interface HighlightsSliceHighlightsPrimary {
  /**
   * Destaque com imagem field in *SectionSliceZone → Highlights_image → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: highlights.highlights.primary.highlight_image[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  highlight_image: prismic.GroupField<
    Simplify<HighlightsSliceHighlightsPrimaryHighlightImageItem>
  >;
}

/**
 * Highlights_image variation for SectionSliceZone Slice
 *
 * - **API ID**: `highlights`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightsSliceHighlights = prismic.SharedSliceVariation<
  "highlights",
  Simplify<HighlightsSliceHighlightsPrimary>,
  never
>;

/**
 * Primary content in *SectionSliceZone → Highlights_text → Primary*
 */
export interface HighlightsSliceHighlightsTextPrimary {
  /**
   * Destaque de texto (sem imagem) field in *SectionSliceZone → Highlights_text → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: highlights.highlightsText.primary.highlight_text[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  highlight_text: prismic.GroupField<
    Simplify<HighlightsSliceHighlightsTextPrimaryHighlightTextItem>
  >;
}

/**
 * Highlights_text variation for SectionSliceZone Slice
 *
 * - **API ID**: `highlightsText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightsSliceHighlightsText = prismic.SharedSliceVariation<
  "highlightsText",
  Simplify<HighlightsSliceHighlightsTextPrimary>,
  never
>;

/**
 * Slice variation for *SectionSliceZone*
 */
type HighlightsSliceVariation =
  | HighlightsSliceHighlights
  | HighlightsSliceHighlightsText;

/**
 * SectionSliceZone Shared Slice
 *
 * - **API ID**: `highlights`
 * - **Description**: Highlights
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightsSlice = prismic.SharedSlice<
  "highlights",
  HighlightsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeTypesDocument,
      HomeTypesDocumentData,
      HomeTypesDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      CommentsZoneSlice,
      CommentsZoneSliceDefaultPrimaryCommentsGroupItem,
      CommentsZoneSliceDefaultPrimary,
      CommentsZoneSliceVariation,
      CommentsZoneSliceDefault,
      HighlightsSlice,
      HighlightsSliceHighlightsPrimaryHighlightImageItem,
      HighlightsSliceHighlightsPrimary,
      HighlightsSliceHighlightsTextPrimaryHighlightTextItem,
      HighlightsSliceHighlightsTextPrimary,
      HighlightsSliceVariation,
      HighlightsSliceHighlights,
      HighlightsSliceHighlightsText,
    };
  }
}
