// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  comments_zone: dynamic(() => import("./CommentsZone")),
  highlights: dynamic(() => import("./SectionSliceZone")),
};
